### ISSUE TITLE
No longer works, not sure which Forge version changed it

### ISSUE THREAD

**Issue by Bidgam** [Dark-Arcana/Speedy-Ladders#6]
Was working fine on Forge 1.16.5-36.0.35 but now as of 0.46 it won't work. I'm not sure if this is a Forge specific issue or another mod now interfering (using Valhelsia 3 modpack).

Ladders show and the audio sound seems to work, but it's as if the ladder is just a physical entity now, you can't use it.

Thanks

**Comment by Lareolan** [comment]
> 
> 
> Was working fine on Forge 1.16.5-36.0.35 but now as of 0.46 it won't work. I'm not sure if this is a Forge specific issue or another mod now interfering (using Valhelsia 3 modpack).
> 
> Ladders show and the audio sound seems to work, but it's as if the ladder is just a physical entity now, you can't use it.
> 
> Thanks

Can confirm. I have tested and starting with Forge 1.16.5-36.0.45 the ladders are broken. Had to roll back to 36.0.44 to get it to work. (I have tested 36.0.45 - 36.0.48, none have worked).

**Comment by AsheX1** [comment]
can confirm the same ladder can be crafted but not used players just hop up and down 
forge update
`Build: 1.16.5-36.0.45 - Wed Mar 03 20:50:47 GMT 2021
	sara:
		Fix a few places where the vanilla method was being called instead of the forge one (#7535)
		
		Cleanup javadocs references slightly, fix a couple spots not using the proper forge hooks, and remove a couple unneeded patches
		Update deprecation comment on isAir`

seems that forge changed something that broke it 
other ladders still work normal ones Quark ect all work normal

**Comment by ghost** [comment]
Thank you for reporting, I have confirmed this with newer versions of forge and will hopefully get it resolved soon.

**Comment by Bidgam** [comment]
Immersive Engineering ladders were reported as broke and they resolved it. Mod dev, maybe contact them to see what happened.

**Comment by ghost** [comment]
Thank you, I was able to quickly figure it out by glancing at their repo. I will release an update soon along with some additional changes.

**Comment by ghost** [comment]
Fixed in 1.16.5-2, thank you
